### PR TITLE
Loading existing routes when using helios as a middleware

### PR DESCRIPTION
**Pull request by framp**
Should fix issues #18 and #30

### CODE REVIEW

**Comment by mtitolo** [comment]
This fix does not work on my Rails 3.2.13 app.

Strike that. It doesn't fix the redirect problem. Jumped the gun...sadly.

**Comment by framp** [comment]
I'm on Rails 3.2.13 too.
Using my fork you're able to use helios routes while keeping your original routes (it's just a Rack::Cascade, actually).

Nothing less, nothing more :)

**Comment by mattt** [comment]
@mtitolo Can you explain what you mean by redirect problem? This patch works for me. Merging it in now.

**Comment by mattt** [comment]
I just cherry-picked 3502156. @framp You may want to check your git configuration, though—attempting to pull from your branch caused git to warn about over-written `.DS_Store` files, which you should probably ignore globally (in `~/.gitignore`).

**Pull request closed without merging**
