### PR TITLE
Push Notification posting support

### PR DESCRIPTION
**Pull request by nwest**
Additions:
- `apn_certificate` and `apn_environment` can be passed in `config.ru` or added as `ENV` variables
- fixes POST `/message`
- some help in `README.md`

### CODE REVIEW

**Comment by nwest** [comment]
exposing POST `/message` isn't perfect because it isn't protected, but I figured it would be alright for now as `/admin` is exposed. 

I'd rather have more `.env` vars for this kind of thing. The configuration block might become too much with more options additions.

**Comment by jstart** [comment]
:+1: This works well for me and seems like a nice endpoint to provide additional push notification abilities.  I am not sure if @mattt wants Houston to be included in the project plus https://github.com/mattt/rack-push-notification

**Comment by nwest** [comment]
@jstart I believe mattt/rack-push-notification is only for registering devices at the moment. mattt/houston is for actually interacting with APN and posting notifications.

**Comment by mattt** [comment]
FYI: I love this pull request. Sorry for taking so long to merge it, @nwest. Thanks so much for sending this!

Y'all have it right: Helios = Rack::PushNotification + Houston.

**Comment by aliirz** [comment]
waiting desperately to have this awesome pull request merged :) :+1:

**Comment by stevederico** [comment]
Also looking forward to this merge.

**Comment by mattt** [comment]
Alright, I squashed everything down into ba3432d and just merged that in. I'll get on re-implementing the web UI from the previous version of `Rack::PushNotification`. Thanks again, @nwest!

**Comment by nwest** [comment]
Cheers!

**Pull request closed without merging**
