### PR TITLE
Make frontend and backend root paths configurable

### PR DESCRIPTION
**Pull request by bartvandendriessche**
Make frontend and backend root paths configurable through frontend_root and backend_root options as mentioned in #23

### CODE REVIEW

**Comment by mtitolo** [comment]
Do you have an example of how this would work when Helios is used as Middleware in Rails?

**Comment by bartvandendriessche** [comment]
This should work:

``` ruby
config.middleware.use Helios::Application, frontend_root: '/frontend', backend_root: '/backend' do
  service :data, model: Dir['*.xcdatamodel*'].first
  service :push_notification
  service :in_app_purchase
  service :passbook
end
```

**Comment by bartvandendriessche** [comment]
It would be nicer I guess if the root options could be provided to services rather than being passed in to the Helios::Application directly.

**Comment by mtitolo** [comment]
:+1: Works great!

**Comment by mattt** [comment]
My intention was to use existing Rack semantics to override the default behavior. `Helios::Application` is the convenient interface, but if you really wanted to customize it, you could mount `Helios::Frontend` and `Helios::Backend` separately at different points. This is, of course, undocumented at the moment, since it's a rather advanced use-case, but that was my thinking.

I'd prefer composition over configuration; do y'all think that documenting this architecture would be sufficient? Or is this a sufficiently common case to warrant a first-class API?

**Comment by mtitolo** [comment]
The biggest problem I see with mounting `Helios::Frontend` and `Helios::Backend` separately (or even with the changes in this patch), is that the Frontend doesn't know what URLs to hit to get its data, since they are hardcoded.

If the Backend is mounted to anything but `/`, the Frontend then tries to hit an endpoint that doesn't exist, and gets no data. If you configure both endpoints at the `Helios::Application` level, then at least the Frontend has a chance of getting notified of a path change for all of its endpoints.

IMHO, setting the path warrants a first-class API.

**Comment by mattt** [comment]
@mtitolo That's a good point. I'll think more about how I'd like to tackle this. At this point, I'm just being picky about the cosmetics of `frontend_root` & `backend_root`.

**Comment by bartvandendriessche** [comment]
You're right, `frontend_root` & `backend_root` parameters make the `Helios::Application` abstraction leaky.

People who are mounting an instance of `Helios::Application` should not pass in parameters to manipulate one of it's subcomponents so directly.

Mounting `Helios::Frontend` and `Helios::Backend` directly sounds like a much better solution, but might feel a bit incoherent to someone who wants to "mount a Helios middleware".

I still think it would be nice if roots (and other settings) could be configured inside the `Helios::Application` block.

**Comment by bartvandendriessche** [comment]
Thinking out loud here, but what if the `Helios::Frontend` app could be aware of the services loaded by `Helios::Backend`.

It would require pulling the `service` method up to `Helios::Application` which would then be able to run the configuration `&block`.

Then `Helios::Application` would be able to configure `Helios::Frontend` based on the captured services (and their settings, like a root path).

`Helios::Frontend` in turn would provide a bootstrap request for the Backbone app, much like how it now does a `OPTIONS` request to fetch the available data models.

This bootstrap request would contain relevant settings of the backend services, such as the root path for the data service, or wether or not the push_notification service is present etc.

**Comment by mattt** [comment]
Here is how things work as of 1316eb3bdd448bb620c5b83bdf3c506722e35e54:

`Helios::Application` has mounts backend services and the frontend at their default paths. If `HELIOS_ADMIN_USERNAME` / `PASSWORD` are set, the frontend will get HTTP basic authentication.

``` ruby
app = Helios::Application.new do
    service :data, model: Dir['*.xcdatamodel*'].first, only: [:create, :read]
    service :push_notification, frontend: false
    service :in_app_purchase
    service :passbook
    service :newsstand
end
```

If you need to customize anything, this can be accomplished using off-the-shelf Rack middleware, like so:

``` ruby
app = Rack::Builder.new do
  map '/admin' do
    use Rack::Auth::Basic, "Restricted Area" do |username, password|
      username == 'admin' and password = "Pa55word"
    end

    run Helios::Frontend.new
  end

  run Helios::Backend.new {
    service :data, root: '/', model: Dir['*.xcdatamodel*'].first, only: [:create, :read]
    service :push_notification
    service :in_app_purchase
    service :passbook
    service :newsstand
  }
end
```

With this commit, the frontend is now aware of which backing services are enabled through an HTTP interface (`Link` headers from `OPTIONS /`). Backend services can now be configured to different roots by setting the `root:` parameter in the `service` call.

**Pull request closed without merging**
