### PR TITLE
Added -h to createdb call in README

### PR DESCRIPTION
**Pull request by mtitolo**
This should help with avoiding #4. Thanks @dmcrodrigues for the info.

### CODE REVIEW

**Comment by dmcrodrigues** [comment]
Glad to help. But i think this can be added as a simple note for 9.1.5 users, what do you think?

_If you are running `createdb` 9.1.5 you should add `-h localhost`. You can check the version of createdb with `--version`._

**Comment by mtitolo** [comment]
Would it break anything if you were to use a newer version of postgres with `-h localhost`?

**Comment by dmcrodrigues** [comment]
It just seems a little bit redundant and at same time does not hide any of the two options for anyone to see, it's just a detail.

**Comment by mattt** [comment]
Thanks, @mtitolo!

**Pull request merged**
